### ISSUE TITLE
Empty comment causes exception

### ISSUE THREAD

**Issue by alimony** [MichaelAquilina/flake8-spellcheck#34] opened 2020-08-12 11:23 UTC
Running this plugin on code with comments that are just `# noqa` gives me:

```
  File "/usr/local/lib/python3.8/site-packages/flake8_spellcheck/__init__.py", line 170, in _parse_token
    and token_info.string.lstrip("#").split()[0] != "noqa:"
IndexError: list index out of range
```

**Comment by MichaelAquilina** [comment] 2020-08-12 12:30
Ah. Definitely a regression from #33 sorry about that. Pin to 0.17.0 for now until we get a fix out.

**Comment by MichaelAquilina** [comment] 2020-08-12 12:30
@3n-k1 would you like to push out a bug fix or would you like me to do it for you?

**Comment by 3n-k1** [comment] 2020-08-12 13:06
might be better if you pushed a fix, I'm not sure how to cleanly fix this

**Comment by 3n-k1** [comment] 2020-08-12 14:04
@alimony could you post a minimal example? i can't reproduce this, the following test case runs fine:

```python
def test_flake8_pragma_regression(self, flake8dir):
    flake8dir.make_example_py("foo = 'bar'  # noqa")
    result = flake8dir.run_flake8()
    assert result.out_lines == []
```
and also the following statements don't throw an error:
```python
"noqa:".split()[0]  # => ['noqa:']
"# noqa:".lstrip('#').split()[0]  # => ['noqa:']
```

**Comment by alimony** [comment] 2020-08-12 14:39
@3n-k1 Turns out it was not the `# noqa` that caused this issue, but something like:

```python
# List of stuff:
#
# foo
# bar

pass
```

E.g. an "empty" comment on line 2 but that I'd say is quite common, and it's a regression regardless.

**Comment by 3n-k1** [comment] 2020-08-12 15:15
thanks for the example! definitely an issue, i hadn't thought of empty comments

so, `.split()` works a lot differently than `.split(' ')`:

```python
"# noqa:".lstrip('#').split(' ')  # => ['', 'noqa:']
"#".lstrip('#').split(' ')  # => ['']
```

however, passing a space as an argument means it only strips spaces, not all whitespace. i think non-space whitespace isn't common in comments like that, but who knows.

the *best* way i to fix this that i can think of without dropping support for python < 3.8 would be something like:

```python
elif (
    token_info.type == tokenize.COMMENT
    and "comments" in self.spellcheck_targets
    # ignore flake8 pragma comments
    and len(token_info.string.lstrip("#").split()) >= 1
    and token_info.string.lstrip("#").split()[0] != "noqa:"
):
```

alternatively, we could create a helper function:

```python
def default_get(the_list, index, default=None):
    the_list[index] if len(the_list) > index else None

...
and get_default(token_info.string.lstrip("#").split(), 0) != "noqa:"
```

@MichaelAquilina i'm more than happy to fix this and write a regression test for it, just not what you would consider the cleanest fix :p

**Comment by alimony** [comment] 2020-08-12 15:31
@3n-k1 Maybe add the condition `and token_info.string.strip() != "#"`?

**Comment by 3n-k1** [comment] 2020-08-12 15:41
that could work. could also split that entire elif into its own function so that it looks cleaner: `and is_valid_comment(token_info)`

**Comment by alimony** [comment] 2020-08-12 15:46
Easier to test too if it's a separate function.

**Comment by 3n-k1** [comment] 2020-08-12 15:54
alright. i'll send a pr in a little bit

**Closed** 2020-08-12 18:07 UTC
Labels: bug

**Comment by MichaelAquilina** [comment] 2020-08-12 18:09
@alimony the issue should be fixed in the latest release (0.18.1). Thanks to @3n-k1 for jumping in to fix this so quickly :)

**Comment by 3n-k1** [comment] 2020-08-12 18:10
glad i could help!

**Comment by alimony** [comment] 2020-08-12 18:58
@MichaelAquilina @3n-k1 Nice! Thanks for the quick turnaround 🥇
